# -*- coding: utf-8 -*-
"""
Anfangs-Feedback fuer alle 4 Eventwochen, so wie von dir bereitgestellt.
Wird beim ersten Start automatisch in die Datenbank geladen (und danach
nie wieder ueberschrieben - spaeteres Feedback im Programm hat Vorrang).

Format je Woche: Liste von (event_order, name, feedback)
"""

SEED_DATA = {
    1: [
        (1, "Gesamte Aufladerückerstattung",
         "Red summon pack would be interesting (newest). Ninjas are not das interessant im Pack (nicht stark genug fuer die Meta)."),
        (2, "Eierschlagen",
         "Good - maybe a better chance for higher amounts of coupons."),
        (3, "Tenten bringt dir Geschenke",
         "Please a pity system :3. Ninjas im Shop sind zu teuer, da Spieler Ingots ausgeben muessen. "
         "Besser erklaeren, wie Gewinner in der Lotterie gewaehlt werden - an vielen Tagen gewinnt niemand!"),
        (4, "Fukurokumarus Geschäft",
         "Red summon pack wird gemocht, koennte aber neuere Red Summons haben. Ninjas sind ok, koennten aber besser sein; "
         "vielleicht eine kleine Menge Sasuke-Shinden-Fragmente?"),
        (5, "Ballonfeier",
         "Shop ist etwas teuer, hat aber schoene Optionen."),
        (6, "Flaggengeschenk",
         "Gilden-Ziele scheinen immer mehr zu hoch zu sein, besonders fuer neuere Server/kleinere Gilden."),
        (7, "Schatzkammer des Eremiten",
         "Rabatt ist nicht gut genug im Vergleich zu anderen Events. Vielleicht die Anzahl an Schluesseln pro Tag erhoehen (auf 10?)."),
        (8, "Glücksbrett", "Gut."),
        (9, "Windspiele",
         "Koennte mehr Items auf Seite 2 haben! Shop ist etwas teuer. Vielleicht etwas wie einzelne Schluessel fuer kleine Punktmengen hinzufuegen?"),
        (10, "Material für den Kampfroben-Fortschritt",
         "In Ordnung, Ingot-Preise sind schlecht."),
        (11, "Zeitlich begrenzter Kampfroben-Fortschritt", "In Ordnung."),
        (12, "Glücksschatzjagd",
         "Sehr schoen! Koennte sogar hoehere Stufen fuer persoenliche Ziele mit einem Ninja o.ae. haben (20 Red Summon Packs?). "
         "Ein Pity-System koennte hier auch einige Spieler retten."),
        (13, "Höhlenschlüssel-Verbrauchsrückerstattung", "Großartig!"),
        (14, "Doppelscheiben-Rad",
         "Nur interessant mit freien Coins. Der Anstieg der Coins fuer den zweiten und folgende Spins ist recht hoch."),
        (15, "Tägliche Auflade-Rückerstattung",
         "Wert nicht so gut (netter Bonus, aber nicht wert, dafuer zu bezahlen), da es taegliche Aufladung ist, ist der Cap recht hoch!"),
        (16, "Frühlings-Glücksbohnen", "Nett."),
        (17, "Sommerliches Treffen",
         "Shop ist teuer, koennte behoben werden, indem mehr Punkte fuer die Austausch-Aufgaben vergeben werden."),
        (18, "Fest der kalten Speisen",
         "Belohnungen koennten etwas besser sein (vielleicht eine kleine Menge Coupons)."),
    ],
    2: [
        (1, "Gesamte Aufladerückerstattung/Überraschungseier",
         "Update the ninjas in the packs. Und in der Event-Beschreibung zeigen, welche Ninjas man mit Ueberraschungseiern bekommen kann."),
        (2, "Einarmiger Bandit", "Good casher event."),
        (3, "Blumen Expertenrangliste", "Auch ein schoenes Event!"),
        (4, "Konoha-Spezialrabatt", "Die Packs mit Trainingspotions aendern, da sie nutzlos sind."),
        (5, "Konoha Rabattfestival", "Ist okay, die Preise sollten geaendert werden, manche Dinge wirken etwas hoch."),
        (6, "Kraft des Neunschwänzigen", "Shop ist zu teuer, vier weitere kostenlose Versuche pro Tag hinzufuegen."),
        (7, "Kommt Zeit kommt Glück", "Dropchance fuer den Jackpot ist schlecht. Und mehr Items fuer den Shop hinzufuegen."),
        (8, "Jubiläums Feuerwerk", "Schoenes Event."),
        (9, "Narutos Geburtstagsfeier", "Nicht schlecht."),
        (10, "Amulett-Verbrauchsbelohnung", "Gutes Event wie immer."),
        (11, "Werkzeug-Training", "Cooles Event, aber mehr Shuriken waeren schoen."),
        (12, "Ninja Unterstützung", "Schoen!"),
        (13, "Anwerbebelohnung", "Die letzten beiden Stufen sind zu hoch."),
        (14, "Wunschlaterne", "Schoen wie immer!"),
        (15, "Wettkampfwoche", "Schoene Art, Spieler zur Arena zu bringen."),
        (16, "Karten Sammeln", "Es ist okay."),
        (17, "Tägliche Verbrauchsrückerstattung", "Nicht beliebt! Inhalt und Preis aendern."),
        (18, "Ninja-Fähigkeitsprüfung", "Sehr schoenes Event, um Sachen fuer manche Kaempfe zu bekommen."),
    ],
    3: [
        (1, "Große Aufladebelohnung",
         "Preise der Stufen senken. Viel zu teuer, 50k fuer alle Stufen ist verrueckt."),
        (2, "Tenten bringt dir Geschenke", "Schoenes Casher-Event!"),
        (3, "Rote Umschläge", "Cooles Event."),
        (4, "9-Sterne-Schatzsuche", "Die Mechanik, dass man seinen Fortschritt verlieren kann, streichen, damit mehr Leute ins Event gehen."),
        (5, "Jo-Nin-Medaillen-Verlängerung", "Schoen wie immer."),
        (6, "Serverübergreifender Gruppenkauf", "Totes Event."),
        (7, "Lose ab 1 Goldbarren", "Auch nicht schlecht."),
        (8, "Verbrauchsrückerstattung", "Die letzten beiden Stufen sind zu teuer, bitte senken."),
        (9, "Heilige Bäume des Konoha-Walds", "Auch ein schoenes Event, Dropchance fuer Ninja-Fragmente ist in den hoeheren Stufen zu niedrig."),
        (10, "Rad des Glücks", "Schoen."),
        (11, "Beschwörungsrückerstattung", "Auch ein schoenes Event."),
        (12, "Schlachtfeldbeschwörung", "Nicht schlecht."),
        (13, "Naruto-Minigame", "Beliebtestes Event."),
        (14, "Aktivitätswundertüte", "Sehr schoenes Event."),
        (15, "Konoha-Fachgeschäft", "Panel 2 ist viel zu teuer."),
        (16, "Tägliche Auflade-Rückerstattung", "Belohnungen sind schlecht, vielleicht waeren Ninja-Fragment-Packs gut."),
        (17, "Konoha-Puzzle", "Schoen fuer manche Sachen."),
        (18, "Auftrags-Mobilmachung", "Keine große Sache."),
    ],
    4: [
        (1, "Narutos Geldbörse", ""),
        (2, "Überraschungseier", ""),
        (3, "Limitierte Aufladeaktion", ""),
        (4, "Einarmiger Bandit", ""),
        (5, "Super-Karneval", ""),
        (6, "Sonnenblumen-Verabredung", ""),
        (7, "Zeitlich begrenzter Punkthändler", ""),
        (8, "Katzengeschenke", ""),
        (9, "Winterwoche", ""),
        (10, "Glücksrad", ""),
        (11, "Zeitlich begrenztes Veredeln", ""),
        (12, "Veredlungsrückerstattung", ""),
        (13, "Kirschblütenfest", ""),
        (14, "Zeitlich begrenztes Anwerben", ""),
        (15, "Nin-Jutsu-Training", ""),
        (16, "Fröhliches Angeln", ""),
        (17, "Goldfisch-Fischen", ""),
        (18, "Heldenprüfung", ""),
        (19, "Zeitlich Begrenztes Ninja-Anwerben", ""),
        (20, "Sommerlager der Ninjaschule", ""),
    ],
}
